### ISSUE TITLE
数据库文件丢失无法启动

### ISSUE THREAD

**Issue by TryHard3r** [MountCloud/BehinderClientSource#1]
MacOS下使用IDEA编译提示数据库文件丢失无法启动
![image](https://user-images.githubusercontent.com/24811079/101520337-4c812180-39bf-11eb-9cbd-5b7a63da35fa.png)

**Comment by MountCloud** [comment]
/src/main/resources/data.db是数据库文件，你是不是项目没有配置对？resources配置成资源文件夹了吗？

**Comment by MountCloud** [comment]
/src/main/resources/data.db是数据库文件，你是不是项目没有配置对？resources配置成资源文件夹了吗？

**Comment by TryHard3r** [comment]
目前自己解决了，不过我是将data.db复制了一份/target/classes目录下，你说的配置资源文件夹也可以，多谢！
