### ISSUE TITLE
请问如何调试内存马？

### ISSUE THREAD

**Issue by sssyyynnngithub** [MountCloud/BehinderClientSource#11]
请问如何调试内存马？如何让内存马第一次执行时断住呢？
谢谢！

**Comment by MountCloud** [comment]
调试内存马，你可以用eclipse或者idea建一个tomcat war项目，写一个servlet或者filter。然后把内存马拷贝到项目，在内存马里打打断点。然后手动new一个内存马实例，调用equals方法传入pageContext。

**Comment by MountCloud** [comment]
没有其他问题这个issues将关闭

**Comment by sssyyynnngithub** [comment]
您好，如果调试反序列化类型的内存马呢？该如何做，不是文件型内存马，谢谢！







在 2022-07-07 09:40:18，"MountCloud" ***@***.***> 写道：

调试内存马，你可以用eclipse或者idea建一个tomcat war项目，写一个servlet或者filter。然后把内存马拷贝到项目，在内存马里打打断点。然后手动new一个内存马实例，调用equals方法传入pageContext。
