### ISSUE TITLE
jdk8该如何修改pom中javafx相关部分

### ISSUE THREAD

**Issue by 11asdad** [MountCloud/BehinderClientSource#15]
请问jdk8该如何修改pom中javafx相关部分？
不改的话会找不到包，直接取消相关注释 maven会因为版本号写的11  而下载11的javafx    导致无法用java8运行
谢谢！

**Comment by MountCloud** [comment]
pom里的javafx相关的都注释掉了，是不是你这边自己做了些调整。

**Comment by 11asdad** [comment]
谢谢回复。
没有调整，java8 clone下来直接运行就提示找不到javxfx，不知道是不是环境有问题，最后换高版本重新逆了
