### ISSUE TITLE
求教一下打包步骤

### ISSUE THREAD

**Issue by icanp1ay** [MountCloud/BehinderClientSource#17]
求教一下打包步骤
下载解压后,直接用idea打开项目,双击Maven里的package,编译生成的文件感觉很小:
![image](https://user-images.githubusercontent.com/15006750/193062969-d67e58ff-fcb0-4a96-87ce-bdf23e7cd5f3.png)
双击没有反应,无法运行.
是还需要配置什么地方么?

**Comment by Drun1baby** [comment]
java -jar xxx.jar 运行即可

**Comment by MountCloud** [comment]
java -jar 那个with-dependencies.jar
