### ISSUE TITLE
3.0-beta-11 版本 aspx 无法获取秘钥

### ISSUE THREAD

**Issue by cseroad** [MountCloud/BehinderClientSource#18]
请教师傅一个问题：
项目构建起来，默认的shell.aspx 无法连接
<img width="990" alt="image" src="https://user-images.githubusercontent.com/59865739/196132491-8f334048-4425-4d5a-9812-c3961c7d81ba.png">

**Comment by chibd2000** [comment]
请问问题解决了吗？
