### ISSUE TITLE
程序实际是Behinder2.0？

### ISSUE THREAD

**Issue by Ar3h** [MountCloud/BehinderClientSource#2]
下载的BehinderClientSource-3.0-beta-6，但是运行起来发现只能支持2.0的马，3.0的马无法运行，抓包发现获取密钥的方式什么的都是2.0版本的，不是3.0的逻辑，怎么回事？
![image](https://user-images.githubusercontent.com/46180221/103618423-e90cf400-4f6a-11eb-89ee-075ad8d78a34.png)

**Comment by MountCloud** [comment]
是不是下错了？

**Comment by Ar3h** [comment]
我下的是这个
![image](https://user-images.githubusercontent.com/46180221/103619180-363d9580-4f6c-11eb-9e45-5e5331b7ad72.png)

我看了看master的，也一样的代码。
就是界面是behinder3.0，但是交互逻辑是2.0的冰蝎
![image](https://user-images.githubusercontent.com/46180221/103619390-97656900-4f6c-11eb-96b1-a27e8eb78728.png)

**Comment by MountCloud** [comment]
那就没错了，是3.0的代码

**Comment by MountCloud** [comment]
可以调试调试看看

**Comment by Ar3h** [comment]
你那边能支持3.0的马吗？
我跟原作者的程序对比了一下流量，明显还是不一样，你这个是2.0交互的流量，能连接上2.0的马。

**Comment by MountCloud** [comment]
嗯嗯我用的是3.0的jsp测试的

**Comment by Ar3h** [comment]
嗯嗯，我测试了一下，jsp的马可以用的，换成php就不能用了。

**Comment by MountCloud** [comment]
php的逻辑也是3.0的，有空的时候我调调php的，可能会比较晚，着急的话你可以先调调哦。

**Comment by Ar3h** [comment]
嗯嗯

**Comment by Ar3h** [comment]
误会了，Behnider3里面就包含的2的代码，只有在连接失败的时候会尝试Behinder2的密钥协商方式。
![image](https://user-images.githubusercontent.com/46180221/104830879-f35db500-58bd-11eb-8451-ca2d1ad3e43c.png)

**Comment by Ar3h** [comment]
连接php的时候报空指针异常，发现getResourceAsStream()获得net/rebeyond/behinder/payload下的文件获取不到，但是能获取到net/rebeyond/behinder/resource下的资源文件，可能跟pom.xml配置有关，我对这个不是很熟，不知道该怎么解决
![image](https://user-images.githubusercontent.com/46180221/104830829-687cba80-58bd-11eb-85cd-b3a9ef8c3293.png)

**Comment by Ar3h** [comment]
解决了，在pom.xml配置中，添加这两行配置，php就可以连接了
![image](https://user-images.githubusercontent.com/46180221/104835778-d20fbf80-58e3-11eb-836f-ae5ce434fb38.png)

**Comment by MountCloud** [comment]
厉害，我合进去
