### ISSUE TITLE
想问下打包问题

### ISSUE THREAD

**Issue by simlelcf** [MountCloud/BehinderClientSource#4]
1.打包后有两个文件一个是Behinder-3.0-beta-6-jar-with-dependencies.jar ,Behinder-3.0-beta-6.jar  两者的区别是啥，只能运行
Behinder-3.0-beta-6-jar-with-dependencies.jar.还有一点想知道原文件打包后只有18兆，这个打包后有50多兆。为啥这么大。
![image](https://user-images.githubusercontent.com/18651522/114648828-068fed80-9d12-11eb-9ada-df08388ffaad.png)

**Comment by MountCloud** [comment]
用Behinder-3.0-beta-6-jar-with-dependencies.jar就可以，一个with-dependencies  jar是包含完整依赖的，一个jar是无依赖的。

**Comment by simlelcf** [comment]
大佬再想问下，这个打包后原本的为啥体积相差这么大

**Comment by MountCloud** [comment]
因为他去掉了javafx，55兆的有javafx

**Comment by simlelcf** [comment]
jdk8是可以的，按理说已经打包了javafx但是jdk11运行后报下面错误
![image](https://user-images.githubusercontent.com/18651522/114650587-1826c480-9d15-11eb-81f1-00f99af6b538.png)

**Comment by MountCloud** [comment]
11需要安装javafx
