### ISSUE TITLE
反编译出来的3.11 源码编译出来的客户端连接上冰蝎默认的木马后没有办法注入内存马

### ISSUE THREAD

**Issue by forktopot** [MountCloud/BehinderClientSource#6]
测试环境：
mac 10.15.5

tomcat 9

使用原版3.11冰蝎 连接相同的马在该环境中是可以注入内存马的

**Comment by forktopot** [comment]
应该是src/main/java/net/rebeyond/behinder/resource/tools 这个路径下的jar包的问题，冰蝎会先根据系统信息去上传对应的jar包然后加载jar包注入内存马然后删除

**Comment by MountCloud** [comment]
> 应该是src/main/java/net/rebeyond/behinder/resource/tools 这个路径下的jar包的问题，冰蝎会先根据系统信息去上传对应的jar包然后加载jar包注入内存马然后删除

多谢反馈，这个issue会在问题修复后关闭。

**Comment by Hvnt3r** [comment]
如果不需要修改对应tools.jar的话，可以将对应文件夹从java目录下移到资源文件夹，可以解决这个问题

**Comment by forktopot** [comment]
> 如果不需要修改对应tools.jar的话，可以将对应文件夹从java目录下移到资源文件夹，可以解决这个问题

大哥，你的意思是将能注入内存马版本的tools 替换掉11版本的tools吗，好像不行哦

**Comment by Hvnt3r** [comment]
> > 如果不需要修改对应tools.jar的话，可以将对应文件夹从java目录下移到资源文件夹，可以解决这个问题
> 
> 大哥，你的意思是将能注入内存马版本的tools 替换掉11版本的tools吗，好像不行哦

我的意思是指用11版本，把tools目录从src目录中copy一份到外面的资源目录下，然后修改加载内存马tools的代码指向新的目录。我怀疑出现这个问题是IDEA的问题，就是当你把src指定为代码目录的时候下面的子目录如果有标记为资源文件的目录的时候会不生效，因此最好把资源跟代码区分开
```java
shellService.uploadFile(libPath, Utils.getResourceData("resource/tools/tools_" + osType + ".jar"), true);
shellService.loadJar(libPath);
shellService.injectMemShell(type, libPath, path, Utils.getKey(shellEntity.getString("password")), isAntiAgent);
```

**Comment by forktopot** [comment]
> > > 如果不需要修改对应tools.jar的话，可以将对应文件夹从java目录下移到资源文件夹，可以解决这个问题
> > 
> > 
> > 大哥，你的意思是将能注入内存马版本的tools 替换掉11版本的tools吗，好像不行哦
> 
> 我的意思是指用11版本，把tools目录从src目录中copy一份到外面的资源目录下，然后修改加载内存马tools的代码指向新的目录。我怀疑出现这个问题是IDEA的问题，就是当你把src指定为代码目录的时候下面的子目录如果有标记为资源文件的目录的时候会不生效，因此最好把资源跟代码区分开
> 
> MainController.java
> 
> ```java
> shellService.uploadFile(libPath, Utils.getResourceData("resource/tools/tools_" + osType + ".jar"), true);
> shellService.loadJar(libPath);
> shellService.injectMemShell(type, libPath, path, Utils.getKey(shellEntity.getString("password")), isAntiAgent);
> ```

不行，我吧资源目录提取出去并修改访问路径依然是不行的，你本地有成功解决这个问题吗？而且同样是将资源目录放在相同路径下的9版本是可以注入成功的，事实上10版本也是注入不成功的，而9版本和10，11版本的区别在于10和11版本多了一个内存马防检测功能

**Comment by Hvnt3r** [comment]
> > > > 如果不需要修改对应tools.jar的话，可以将对应文件夹从java目录下移到资源文件夹，可以解决这个问题
> > > 
> > > 
> > > 大哥，你的意思是将能注入内存马版本的tools 替换掉11版本的tools吗，好像不行哦
> > 
> > 
> > 我的意思是指用11版本，把tools目录从src目录中copy一份到外面的资源目录下，然后修改加载内存马tools的代码指向新的目录。我怀疑出现这个问题是IDEA的问题，就是当你把src指定为代码目录的时候下面的子目录如果有标记为资源文件的目录的时候会不生效，因此最好把资源跟代码区分开
> > MainController.java
> > ```java
> > shellService.uploadFile(libPath, Utils.getResourceData("resource/tools/tools_" + osType + ".jar"), true);
> > shellService.loadJar(libPath);
> > shellService.injectMemShell(type, libPath, path, Utils.getKey(shellEntity.getString("password")), isAntiAgent);
> > ```
> 
> 不行，我吧资源目录提取出去并修改访问路径依然是不行的，你本地有成功解决这个问题吗？而且同样是将资源目录放在相同路径下的9版本是可以注入成功的，事实上10版本也是注入不成功的，而9版本和10，11版本的区别在于10和11版本多了一个内存马防检测功能

我本地现在可以正常使用重新编译的11版本的，关键看你编译后的tools_x.jar的大小是否变化了，我这边之前编译后的toolsjar包会变成1.5m大小，原本是900k，变成1.5m的jar包损坏了，也就无法注入，因此想办法不要让idea更改对应jar就可以了

**Comment by 22CB7139** [comment]
> > 修改pom.xml
> > ```
> >   <resources>
> >       <resource>
> >         <directory>src/main/resources</directory>
> >         <filtering>true</filtering>
> >       </resource>
> >       <resource>
> >         <directory>src/main/java</directory>
> >         <filtering>true</filtering>
> >       </resource>
> >     </resources>
> >     <plugins>
> >       <plugin>
> >         <groupId>org.apache.maven.plugins</groupId>
> >         <artifactId>maven-resources-plugin</artifactId>
> >         <configuration>
> >           <encoding>UTF-8</encoding>
> >           <nonFilteredFileExtensions>
> >             <nonFilteredFileExtension>xml</nonFilteredFileExtension>
> >             <nonFilteredFileExtension>fxml</nonFilteredFileExtension>
> >             <nonFilteredFileExtension>jpg</nonFilteredFileExtension>
> >             <nonFilteredFileExtension>png</nonFilteredFileExtension>
> >             <nonFilteredFileExtension>css</nonFilteredFileExtension>
> >             <nonFilteredFileExtension>dll</nonFilteredFileExtension>
> >             <nonFilteredFileExtension>jar</nonFilteredFileExtension>
> >             <nonFilteredFileExtension>js</nonFilteredFileExtension>
> >             <nonFilteredFileExtension>html</nonFilteredFileExtension>
> >             <nonFilteredFileExtension>gif</nonFilteredFileExtension>
> >             <nonFilteredFileExtension>asp</nonFilteredFileExtension>
> >             <nonFilteredFileExtension>php</nonFilteredFileExtension>
> >             <nonFilteredFileExtension>jar</nonFilteredFileExtension>
> >             <nonFilteredFileExtension>32</nonFilteredFileExtension>
> >             <nonFilteredFileExtension>64</nonFilteredFileExtension>
> >             <nonFilteredFileExtension>bak</nonFilteredFileExtension>
> >           </nonFilteredFileExtensions>
> >         </configuration>
> >       </plugin>
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > mvn clean package -DskipTests
> 
> 这样不行吧，你这样配置是把所有必要的文件都给过滤掉了。

nonFilteredFileExtension是指定不需要重新编码文件类型，并没有过滤文件。

**Comment by MountCloud** [comment]
> > > 修改pom.xml
> > > ```
> > >   <resources>
> > >       <resource>
> > >         <directory>src/main/resources</directory>
> > >         <filtering>true</filtering>
> > >       </resource>
> > >       <resource>
> > >         <directory>src/main/java</directory>
> > >         <filtering>true</filtering>
> > >       </resource>
> > >     </resources>
> > >     <plugins>
> > >       <plugin>
> > >         <groupId>org.apache.maven.plugins</groupId>
> > >         <artifactId>maven-resources-plugin</artifactId>
> > >         <configuration>
> > >           <encoding>UTF-8</encoding>
> > >           <nonFilteredFileExtensions>
> > >             <nonFilteredFileExtension>xml</nonFilteredFileExtension>
> > >             <nonFilteredFileExtension>fxml</nonFilteredFileExtension>
> > >             <nonFilteredFileExtension>jpg</nonFilteredFileExtension>
> > >             <nonFilteredFileExtension>png</nonFilteredFileExtension>
> > >             <nonFilteredFileExtension>css</nonFilteredFileExtension>
> > >             <nonFilteredFileExtension>dll</nonFilteredFileExtension>
> > >             <nonFilteredFileExtension>jar</nonFilteredFileExtension>
> > >             <nonFilteredFileExtension>js</nonFilteredFileExtension>
> > >             <nonFilteredFileExtension>html</nonFilteredFileExtension>
> > >             <nonFilteredFileExtension>gif</nonFilteredFileExtension>
> > >             <nonFilteredFileExtension>asp</nonFilteredFileExtension>
> > >             <nonFilteredFileExtension>php</nonFilteredFileExtension>
> > >             <nonFilteredFileExtension>jar</nonFilteredFileExtension>
> > >             <nonFilteredFileExtension>32</nonFilteredFileExtension>
> > >             <nonFilteredFileExtension>64</nonFilteredFileExtension>
> > >             <nonFilteredFileExtension>bak</nonFilteredFileExtension>
> > >           </nonFilteredFileExtensions>
> > >         </configuration>
> > >       </plugin>
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > mvn clean package -DskipTests
> > 
> > 
> > 这样不行吧，你这样配置是把所有必要的文件都给过滤掉了。
> 
> nonFilteredFileExtension是指定不需要重新编码文件类型，并没有过滤文件。

ok 多谢提供
