### ISSUE TITLE
编译完提示数据库文件丢失

### ISSUE THREAD

**Issue by bitian** [MountCloud/BehinderClientSource#7]
编译完提示数据库文件丢失，不知道是哪里出错了？

**Comment by MountCloud** [comment]
数据库文件在资源路径里。
这个问题是没有正确识别到资源路径。
出现这个问题需要手动添加一下资源路径：src/main/resources

**Comment by bitian** [comment]
我在生成jar包时配置时添加了路径等信息如下：
![QQ截图20210912213351](https://user-images.githubusercontent.com/14858638/132989744-f7d015cb-703c-43a4-aa78-d1972160e238.png)
![QQ截图20210912213426](https://user-images.githubusercontent.com/14858638/132989748-f0d91198-2717-4ac4-be33-35e507418627.png)
编译后运行还是提示“数据库文件丢失，无法启动。”，编译后的jar包30多M，麻烦再看看哪里错了，谢谢！

**Comment by MountCloud** [comment]
编译后的jar，需要将数据库文件放到jar同目录下运行，这个你可以参考原版冰蟹的文件列表。

**Comment by bitian** [comment]
原来如此，感谢！
