### ISSUE TITLE
请问有遇到过编译完成后右键无反应的情况吗

### ISSUE THREAD

**Issue by sv3nbeast** [MountCloud/BehinderClientSource#8]
![image](https://user-images.githubusercontent.com/55974091/149914058-2d9386d8-12ff-4bda-ad73-52a124a6485e.png)
![image](https://user-images.githubusercontent.com/55974091/149914102-027d668f-2a2c-4ec9-9163-b8e2226cc065.png)

**Comment by think3t** [comment]
> ![image](https://user-images.githubusercontent.com/55974091/149914058-2d9386d8-12ff-4bda-ad73-52a124a6485e.png) ![image](https://user-images.githubusercontent.com/55974091/149914102-027d668f-2a2c-4ec9-9163-b8e2226cc065.png)

和你一样，JDK1.8，macOS和Windows都一样，右键无任何反应。

**Comment by whami-root** [comment]
我将Main class改为net/rebeyond/behinder/ui/Launcher.java后解决了这个问题，你们可以试试

**Comment by F4ded** [comment]
m1 mac zujujdk 8u322 碰到了同样的问题，师傅们有解决办法吗

**Comment by Vicl1fe** [comment]
在MainController中142那里输出异常，运行的时候就会发现错误信息了，因为这个所以才导致了无法右键
<img width="442" alt="image" src="https://user-images.githubusercontent.com/48847838/168405614-4deb8581-cc16-4ab5-998f-195d8d5f6220.png">
报错信息是Sqlite损坏，参考文章为https://blog.csdn.net/yangshuai518/article/details/103488762

问题没打算深究，所以我这里的解决办法是直接将data.db指定为绝对路径，我这里指定的是资源目录下的路径data.db
<img width="979" alt="image" src="https://user-images.githubusercontent.com/48847838/168405716-33ab129b-b872-4959-ab79-6b146bb4ab48.png">

此时工作正常
<img width="386" alt="image" src="https://user-images.githubusercontent.com/48847838/168405751-03738394-7986-4795-bf0c-ae0feb319e9e.png">

放心，打包的时候可以再将绝对路径改成相对路径，然后和Behinder.jar放在同一目录即可

**Comment by MountCloud** [comment]
之前太忙没时间搞修复，可以用最新的4.0.2，这个版本是我修复过一些基础功能的。
